name: package_info_plus_windows
description: Windows implementation of the package_info_plus plugin
version: 0.2.0
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  package_info_plus_platform_interface: ^0.3.0
  ffi: ^0.1.3
  flutter:
    sdk: flutter
  win32: ^1.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2
