name: share_plus
description: Flutter plugin for sharing content via the platform share UI, using the ACTION_SEND intent on Android and UIActivityViewController on iOS.
version: 1.2.0
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/

flutter:
  plugin:
    platforms:
      android:
        package: dev.fluttercommunity.plus.share
        pluginClass: SharePlusPlugin
      ios:
        pluginClass: FLTSharePlusPlugin
      linux:
        default_package: share_plus_linux
      web:
        default_package: share_plus_web
      windows:
        default_package: share_plus_windows

dependencies:
  meta: ^1.0.5
  mime: ^0.9.7
  flutter:
    sdk: flutter
  share_plus_platform_interface: ^1.2.0
  share_plus_linux: ^1.1.0
  share_plus_windows: ^0.1.0
  share_plus_web: ^0.1.0

dev_dependencies:
  test: ^1.3.0
  mockito: ^3.0.0
  flutter_test:
    sdk: flutter
  integration_test: ^0.9.1
  pedantic: ^1.8.0
  url_launcher: ^5.7.2

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"
