name: share_plus
description: Flutter plugin for sharing content via the platform share UI, using the ACTION_SEND intent on Android and UIActivityViewController on iOS.
version: 2.1.0-nullsafety.0
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/

flutter:
  plugin:
    platforms:
      android:
        package: dev.fluttercommunity.plus.share
        pluginClass: SharePlusPlugin
      ios:
        pluginClass: FLTSharePlusPlugin
      linux:
        default_package: share_plus_linux
      macos:
        default_package: share_plus_macos
      web:
        default_package: share_plus_web
      windows:
        default_package: share_plus_windows

dependencies:
  meta: ^1.0.5
  mime: ^1.0.0-nullsafety
  flutter:
    sdk: flutter
  share_plus_platform_interface: ^2.0.0-nullsafety
  share_plus_linux: ^2.0.0-nullsafety
  share_plus_macos: ^0.1.0-nullsafety
  share_plus_windows: ^0.2.0-nullsafety
  share_plus_web: ^0.2.0-nullsafety

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2

environment:
  sdk: '>=2.12.0-259.9.beta <3.0.0'
  flutter: ">=1.12.13+hotfix.5"
