name: device_info_plus
description: Flutter plugin providing detailed information about the device
  (make, model, etc.), and Android or iOS version the app is running on.
version: 1.0.0-nullsafety.1
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/

flutter:
  plugin:
    platforms:
      android:
        package: dev.fluttercommunity.plus.device_info
        pluginClass: DeviceInfoPlusPlugin
      ios:
        pluginClass: FLTDeviceInfoPlusPlugin
      linux:
        default_package: device_info_plus_linux
      web:
        default_package: device_info_plus_web
      macos:
        default_package: device_info_plus_macos
      windows:
        default_package: device_info_plus_windows

dependencies:
  flutter:
    sdk: flutter
  device_info_plus_platform_interface: ^1.0.0-nullsafety
  device_info_plus_linux: ^1.0.0-nullsafety
  device_info_plus_macos: ^1.0.0-nullsafety
  device_info_plus_web: ^1.0.0-nullsafety
  device_info_plus_windows: ^1.0.0-nullsafety

dev_dependencies:
  test: ^1.3.0
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"
