name: android_intent_plus
description: Flutter plugin for launching Android Intents. Not supported on iOS.
version: 0.5.0-nullsafety.1
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/

flutter:
  plugin:
    platforms:
      android:
        package: dev.fluttercommunity.plus.androidintent
        pluginClass: AndroidIntentPlugin

dependencies:
  flutter:
    sdk: flutter

  platform: ^3.0.0-nullsafety
  meta: ^1.3.0-nullsafety

dev_dependencies:
  flutter_test:
    sdk: flutter

  test: ^1.16.0-nullsafety
  mockito: ^5.0.0-nullsafety
  pedantic: ^1.10.0-nullsafety

environment:
  sdk: ">=2.12.0-133.7.beta <3.0.0"
  flutter: ">=1.12.13+hotfix.5"
