name: device_info_plus_linux
description: Linux implementation of the device_info_plus plugin
homepage: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/device_info_plus_linux
version: 0.1.0

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  device_info_plus_platform_interface: ^0.2.0
  file: ^5.2.1
  flutter:
    sdk: flutter
  meta: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
