name: package_info_plus_macos
description: macOS implementation of the package_info_plus plugin.
version: 0.1.0
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/packages/

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: FLTPackageInfoPlugin
        fileName: package_info_plus_macos.dart

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: '>=1.20.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.8.0
