name: battery_plus_windows
description: Windows implementation of the battery_plus plugin
homepage: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/battery_plus_windows
version: 0.1.0

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  battery_plus_platform_interface: ^0.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: BatteryPlusWindowsPlugin
