name: connectivity_plus_linux
description: Linux implementation of the connectivity_plus plugin
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/
version: 0.4.0-nullsafety.0

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
#  connectivity_plus_platform_interface: ^0.5.0-nullsafety.0
#  dbus: ^0.1.0
  connectivity_plus_platform_interface:
    path: ../connectivity_plus_platform_interface
  dbus:
    git:
      url: git://github.com/robert-ancell/dbus.dart.git
      ref: null-safety
  meta: ^1.3.0-nullsafety.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0-nullsafety.7
  pedantic: ^1.10.0
  build_runner: ^1.11.0

flutter:
  plugin:
    platforms:
      linux:
        dartPluginClass: ConnectivityLinux
        pluginClass: none
