name: device_info_plus_web
description: An implementation for the web platform of the Flutter `device_info_plus` plugin.
version: 0.2.0
homepage: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/device_info_plus_web

flutter:
  plugin:
    platforms:
      web:
        pluginClass: DeviceInfoPlugin
        fileName: device_info_plus_web.dart

dependencies:
  device_info_plus_platform_interface: ^0.2.0
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter

dev_dependencies:
  test: any
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test: ^0.9.1
  mockito: ^4.1.2

environment:
  sdk: '>=2.6.0 <3.0.0'
  flutter: '>=1.12.13+hotfix.4'
