name: android_alarm_manager_example
description: Demonstrates how to use the android_alarm_manager_plus plugin.

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  android_alarm_manager_plus:
    path: ../
  shared_preferences: ^0.5.6
  integration_test: ^0.9.2
  path_provider: ^1.3.1

dev_dependencies:
  espresso: ^0.0.1+5
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0

flutter:
  uses-material-design: true
