name: share_example
description: Demonstrates how to use the share_plus plugin.

dependencies:
  flutter:
    sdk: flutter
  share_plus:
    path: ../
  image_picker: ^0.6.7+4

dev_dependencies:
  flutter_driver:
    sdk: flutter
  integration_test: ^0.9.1
  pedantic: ^1.9.2

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.9.1+hotfix.2 <2.0.0"
