name: battery_plus_linux
description: Linux implementation of the battery_plus plugin
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/
version: 0.3.0-nullsafety

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  battery_plus_platform_interface: ^0.4.0-nullsafety
  dbus: ^0.2.0
  flutter:
    sdk: flutter
  meta: ^1.3.0-nullsafety

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0-nullsafety
  pedantic: ^1.10.0-nullsafety

flutter:
  plugin:
    platforms:
      linux:
        dartPluginClass: BatteryLinux
        pluginClass: none
