name: connectivity_plus_web
description: An implementation for the web platform of the Flutter `connectivity_plus` plugin. This uses the NetworkInformation Web API, with a fallback to Navigator.onLine.
version: 0.5.0
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/

flutter:
  plugin:
    platforms:
      web:
        pluginClass: ConnectivityPlugin
        fileName: connectivity_plus_web.dart

dependencies:
  connectivity_plus_platform_interface: ^0.3.0
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter

dev_dependencies:
  test: any
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test: ^0.9.1
  mockito: ^4.1.1
  pedantic: ^1.9.2

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: '>=1.20.0'
