name: connectivity_plus_macos
description: macOS implementation of the connectivity_plus plugin.
version: 0.2.0
homepage: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/connectivity_plus_macos

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: ConnectivityPlugin

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  connectivity_plus_platform_interface:
    path: ../connectivity_plus_platform_interface
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.8.0
