name: sensors_plus_web
description: The web implementation of sensors_plus
version: 0.1.0
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/packages/

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=1.20.0'

flutter:
  plugin:
    platforms:
      web:
        pluginClass: SensorsPlugin
        fileName: sensors_plus_web.dart

dependencies:
  flutter:
    sdk: flutter
  sensors_plus_platform_interface: ^0.1.0
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  test: any
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test: ^0.9.1
  mockito: ^4.1.2
