name: share_plus_platform_interface
description: A common platform interface for the share_plus plugin.
homepage: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/share_plus
version: 0.1.0

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8
  mime: ^0.9.7
  plugin_platform_interface: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test: ^0.9.1
  mockito: ^3.0.0
  pedantic: ^1.8.0
  test: ^1.3.0

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"
