name: connectivity_plus_example
description: Demonstrates how to use the connectivity_plus plugin.

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus:
    path: ../

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any
  integration_test: ^0.9.1
  pedantic: ^1.8.0
  connectivity: ^2.0.2

flutter:
  uses-material-design: true
