name: battery_plus
description: Flutter plugin for accessing information about the battery state(full, charging, discharging).
version: 1.0.0-nullsafety.0
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/

flutter:
  plugin:
    platforms:
      android:
        package: dev.fluttercommunity.plus.battery
        pluginClass: BatteryPlusPlugin
      ios:
        pluginClass: FLTBatteryPlusPlugin
      linux:
        default_package: battery_plus_linux
      macos:
        default_package: battery_plus_macos
      web:
        default_package: battery_plus_web
      windows:
        default_package: battery_plus_windows

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.0.5
  battery_plus_platform_interface: ^0.4.0-nullsafety
  battery_plus_linux: ^0.3.0-nullsafety
  battery_plus_macos: ^0.3.0-nullsafety
  battery_plus_web: ^0.4.0-nullsafety
  battery_plus_windows: ^0.3.0-nullsafety

dev_dependencies:
  flutter_test:
    sdk: flutter

  async: ^2.0.8
  plugin_platform_interface: ^1.0.0
  test: ^1.16.0-nullsafety
  pedantic: ^1.10.0-nullsafety

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: '>=1.12.13+hotfix.5'
