name: skip_required_checks

on:
  pull_request:
    paths:
      - "docs/**"
      - "website/**"
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required as only docs or non-plugin files changed"'
